//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using NatureMVC.Models.Entity;

namespace NatureMVC
{
    [MetadataType(typeof(ClientForeignKeys))]
    public partial class ClientForeignKey
    {
        public int Id_FK { get; set; }
        public int Id_C { get; set; }
        public int Id_RD { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual RangeData RangeData { get; set; }
    }
}
