//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using NatureMVC.Models.Entity;

namespace NatureMVC
{
    using System;
    using System.Collections.Generic;

    [MetadataType(typeof(ClientRequests))]
    public partial class ClientRequest
    {
        public int Id_R { get; set; }
        public System.DateTime Checkin { get; set; }
        public System.DateTime Checkout { get; set; }
        public string Request { get; set; }
        public int Adult { get; set; }
        public Nullable<int> Children { get; set; }
        public int Id_C { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
