//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NatureMVC
{
    using System;
    using System.Collections.Generic;
    using NatureMVC.Models.Entity;
    using  System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(InfoClients))]
    public partial class InfoClient
    {
        public long Phone { get; set; }
        public string Email { get; set; }
        public int Id_C { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
