//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NatureMVC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NatureEntities : DbContext
    {
        public NatureEntities()
            : base("name=NatureEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClientRequest> ClientRequests { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<InfoClient> InfoClients { get; set; }
        public virtual DbSet<ClientForeignKey> ClientForeignKeys { get; set; }
        public virtual DbSet<DataClient> DataClients { get; set; }
        public virtual DbSet<RangeData> RangeDatas { get; set; }
    }
}
