//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace NatureMVC
{
    using System;
    using System.Collections.Generic;
    using NatureMVC.Models.Entity;

    [MetadataType(typeof(RangeDatas))]
    public partial class RangeData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RangeData()
        {
            this.ClientForeignKeys = new HashSet<ClientForeignKey>();
        }
    
        public int Id_RD { get; set; }
        public System.DateTime RangeData1 { get; set; }
        public int Id_D { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientForeignKey> ClientForeignKeys { get; set; }
        public virtual DataClient DataClient { get; set; }
    }
}
